version: '3'

services:

  # Standard database
  mysql:
    container_name: mysql
    image: mysql:8.0.11
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "rootpass"
      MYSQL_DATABASE: "database"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "userpass"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: always
    volumes:
      - "./docker/db/mysql:/var/lib/mysql"

  # For Django application
  django-app:
    container_name: django-app
    build: ./django-app
    working_dir: /home/docker/app
    command: > 
      /bin/bash -c "source ~/.bash_profile && \
                    python manage.py migrate && \
                    python manage.py collectstatic --noinput && \
                    supervisord -n" #example
    ports:
      - 8001:80
    depends_on:
      - python-webapp-base
      - mysql

  # Python Web Application Environment
  python-webapp-base:
    build: "./docker/base"
